GET http://localhost:3000/api/me
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNjUwNDQ4Mjc4LCJzdWIiOiI5ZDA2ZmNhYS0xMTMyLTQ1NjctYjAxNS1mMWQ3YTRlZWJlNDAiLCJlbWFpbCI6ImltZnVubmllZUBnbWFpbC5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7fSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQifQ.8GB9CF5BbHCHxIW3Qto30HM1cPYigzyKEhcOPBrxVz0